# Generated by Django 5.1.4 on 2025-01-19 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superman', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='describe',
            new_name='discribe',
        ),
    ]
