# Generated by Django 5.1.4 on 2025-01-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superman', '0007_alter_contact_discribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='discribe',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
